[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"   # <- aponta p/ as functions

[functions]
  directory = "netlify/functions"   # <- redundante, mas ajuda
  node_bundler = "esbuild"

